<?php
$str = '{"data":[{"title":"Alfa Romeo", "url":"http://www.alfaromeo.com.tr/"},{"title":"Audi", "url":"http://www.audi.com.tr"},{"title":"BMC", "url":"http://www.bmcsan.com/"},{"title":"BMW", "url":"http://www.bmw.com.tr"},{"title":"Borusan Oto", "url":"http://www.borusanoto.com/"},{"title":"Citroen", "url":"http://www.citroen.com.tr/"},{"title":"Dacia", "url":"http://www.dacia.com.tr/"},{"title":"Daewoo", "url":"http://www.daewoo-tr.com/"},{"title":"Ferrari", "url":"http://www.ferrari.com.tr/"},{"title":"Ford", "url":"http://www.ford.com.tr/"},{"title":"HMF", "url":"http://www.hmf.com.tr/"},{"title":"Honda", "url":"http://www.honda.com.tr"},{"title":"Hyundai", "url":"http://www.hyundai.com.tr"},{"title":"Isuzu", "url":"http://www.isuzu.com.tr/"},{"title":"Karsan", "url":"http://www.karsan.com.tr/"},{"title":"Kia", "url":"http://www.kia.com.tr/"},{"title":"Lada", "url":"http://www.celikmotor.com.tr/"},{"title":"Land Rover", "url":"http://www.landrover.com.tr/"},{"title":"MAN", "url":"http://www.man.com.tr/"},{"title":"Maserati", "url":"http://www.maserati.com.tr/"},{"title":"Mazda", "url":"http://www.mazda.com.tr/"},{"title":"Mercedes-Benz", "url":"http://www.mercedes-benz.com.tr/"},{"title":"Mini", "url":"http://www.mini.com.tr/"},{"title":"Motosan", "url":"http://www.motosan.com/"},{"title":"Nissan", "url":"http://www.nissan.com.tr/"},{"title":"Opel", "url":"http://www.opel.com.tr"},{"title":"Otokar", "url":"http://www.otokar.com.tr/"},{"title":"Peugeot", "url":"http://www.peugeot.com.tr/"},{"title":"Porsche", "url":"http://www.porsche.com.tr/"},{"title":"Proton", "url":"http://www.protontr.com/"},{"title":"Renault", "url":"http://www.renault.com.tr/"},{"title":"Saab", "url":"http://www.saab.com.tr/"},{"title":"Seat", "url":"http://www.seat.com.tr"},{"title":"Skoda", "url":"http://www.skoda.com.tr"},{"title":"Subaru", "url":"http://www.subaru.com.tr/"},{"title":"Suzuki", "url":"http://www.suzuki.com.tr/"},{"title":"Tata", "url":"http://www.tata.com.tr/"},{"title":"Temsa", "url":"http://www.temsa.com.tr/"},{"title":"Tofaş", "url":"http://www.tofas.com.tr/"},{"title":"Toyota", "url":"http://www.toyotasa.com.tr/"},{"title":"Türk Traktör", "url":"http://www.turktraktor.com.tr/"},{"title":"Ulu Motor", "url":"http://www.ulumotor.com/"},{"title":"Volkswagen", "url":"http://www.vw.com.tr/"},{"title":"Volvo", "url":"http://www.volvocars.com.tr/"}]}';

$json = json_decode($str);

foreach($json->data as $item){

    echo 'UPDATE crs_brands SET brd_website = "'.trim($item->url).'" WHERE brd_title = "'.trim($item->title).'";<br />';
  
}
?>